name: crewai-multi-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=24.0
  - numpy=1.26.4
  - pandas=2.2.1
  - jupyter=1.0.0
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - pip:
      - crewai==0.28.8
      - crewai_tools==0.1.6
      - langchain_community==0.0.29
      - langchain_groq==0.1.0
      - pydantic>=2.0.0
      - transformers==4.38.2
      - huggingface-hub==0.20.3
      - tokenizers==0.15.2
      - "-e ../simple_agent_common/."
