data:
  paths:
    input_dir: "data"
    env: "~/src/python/.env"
    metrics: "output/metrics"

benchmark:
  iterations: 3
  total_questions: 20

model:
    name: "llama3-70b-8192"
    temperature: 0.01
    max_tokens: 1000
    max_calls: 4
    pause_time: 30
    token_limit: 90000
    stop_after_attempt: 3
    wait_multiplier: 60
    wait_min: 180
    wait_max: 300