name: autogen-multi-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyyaml
  - numpy
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - pip:
      - pyautogen>=0.2.0
      - groq>=0.4.2
      - transformers==4.38.2
      - psutil>=5.9.7
      - python-dotenv>=1.0.0
      - typing-extensions>=4.8.0
      - pydantic>=2.4,<3
      - tenacity==8.5.0
      - "-e ../simple_agent_common" 